baseURL = 'https://blog.wolfstarmagic.com/'
languageCode = 'en-us'
theme = 'anatole'
title = 'Wolf Star Magic'

[params]
title = "Wolf Star Magic"
author = "Sam Johnson"
profilePicture = "/headshot.jpg"
github = "https://github.com/wolfstarmagic"
facebook = "https://facebook.com/praveenjuge"
sitename = "Wolf Star Magic"
twitter = "@wolfstarmagic"

[taxonomies]
tag = "tags"
category = "categories"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

  [languages.ja]
    languageName = "Arabic"
    languageCode = "ja"
    weight = 2
